In [3]:
#📌 1. Import NumPy

import numpy as np

In [6]:
# 📌 2. Creating Arrays

In [7]:
# 1D array
a = np.array([1, 2, 3])
print(a)


[1 2 3]


In [8]:
# 2D array
b = np.array([[1, 2], [3, 4]])
print(b)

[[1 2]
 [3 4]]


In [9]:
# Zeros, Ones, Identity
print(np.zeros((2, 3)))
print(np.ones((2, 2)))
print(np.eye(3))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
